### ISSUE TITLE
Design flow of errors from backend models to frontend

### ISSUE THREAD

**Issue by lfse-slafleur** [Project-OMOTES/architecture-documentation#13]
Figure out the possible types of errors and how to get any relevant errors to the frontend when necessary.
Will need to discuss with simulator, optimizer & KPI module teams on what type of errors they expect will be relevant to show to the user.

We need to design for the use case: "There is an issue that the user can fix by themselves, present the error so they know the issue and can figure out the fix." For instance, missing profile, during optimization/simulation no solution turns out to be feasible because.., an error that the validator did not pick up.
Also, a user needs to be shown something whenever something goes wrong. So there will be a class of errors that need to land somewhere where a helpdesk can pick them up but a 'call helpdesk' error is shown to the user. Probably the frontend needs to be able to route these errors as the filter between what is shown is different for MapEditor and TPG.

**Comment by TNO-SlaFleur** [comment]
Implementation on worker-side done. Waiting on orchestrator-side & sdk-side. Will document once fully implemented.

**Comment by TNO-SlaFleur** [comment]
Tbd:
- [ ] https://github.com/Project-OMOTES/orchestrator/issues/9
- [ ] https://github.com/Project-OMOTES/orchestrator/issues/14

**Comment by lfse-slafleur** [comment]
@lfse-slafleur
