### ISSUE TITLE
Design queueing strategy for RabbitMQ as part of orchestrator work

### ISSUE THREAD

**Issue by lfse-slafleur** [Project-OMOTES/architecture-documentation#14]

**Comment by TNO-SlaFleur** [comment]
Implementation on worker-side done. Waiting on orchestrator-side & sdk-side. Will document once fully implemented.

**Comment by TNO-SlaFleur** [comment]
Design is done, mostly documentation still needed. Started with documenting already:
https://github.com/Project-OMOTES/architecture-documentation/blob/main/sdk/sdk.md
